### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by MNDZio** [MNDZio/arquitectos#1]
- [x] e-mail Sign-In
    * Send password / verification email to members
2. Multiple PDF Upload with Date Picker (Month/Year)
3. PDF Upload for 'Copilado PDF'
4. Slider Controller / Caption
5. Project Details 
    - [x] Ubicacion
    - [x] Logo
    - [x] PDF for Juridico and Construcion

**Comment by Faryshta** [comment]
ya esta el email signin

**Comment by Faryshta** [comment]
¿es un sólo pdf jurídico y uno sólo de construcción? por proyecto?

**Comment by drunkvegas** [comment]
Si.

**Comment by Faryshta** [comment]
ok deja sigo modificando entonces lo de proyecto
